# Generated by Django 4.1.7 on 2024-07-19 20:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('Company_code_name', models.CharField(max_length=10)),
                ('time_bought', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('buyer_name', models.CharField(max_length=300)),
                ('buyer_number', models.CharField(max_length=11)),
                ('payment_status', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.seller')),
            ],
        ),
    ]
