# Generated by Django 4.1.7 on 2024-07-19 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_price_product_price1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_details',
            options={'verbose_name_plural': 'Product_details'},
        ),
        migrations.RemoveField(
            model_name='seller',
            name='time_bought',
        ),
        migrations.AddField(
            model_name='product_details',
            name='time_bought',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
