# Generated by Django 4.1.7 on 2024-07-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_details_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product_details'},
        ),
        migrations.DeleteModel(
            name='Product_details',
        ),
    ]
