# Generated by Django 4.1.7 on 2024-07-20 19:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_delete_product_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('buyer_name', models.CharField(max_length=300)),
                ('buyer_number', models.CharField(max_length=11)),
                ('payment_status', models.BooleanField(default=False)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('price_paid', models.FloatField()),
                ('price_owing', models.FloatField()),
                ('time_bought', models.DateField(default=datetime.datetime.today)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.seller')),
            ],
        ),
    ]
