# Generated by Django 4.1.7 on 2024-07-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='price_owing',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='price_paid',
            field=models.FloatField(blank=True),
        ),
    ]
