# Generated by Django 4.1.7 on 2024-08-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_detail_price_owing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='seller',
        ),
    ]
